name: locopalettes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - scikit-learn
  - scikit-image
  - numpy
  - scipy
  - py-opencv
  - pillow
  - cvxopt
  - pip
  - git
  - cython
  - cvxpy
  - pytorch
  - torchvision
  - pip:
     - qtwidgets
     - git+https://github.com/yig/python-qtwidgets#egg=qtwidgets
     - qtpy
     - matplotlib
     - seaborn
     - pyside6
     - git+https://github.com/cocodataset/panopticapi.git
